/* Arduino SdFat Library
 * Copyright (C) 2010 by William Greiman
 * Revision Date: 08/18/2011 (Olver Jones)
 *
 * This file is part of the Arduino SdFat Library
 *
 * This Library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This Library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Arduino SdFat Library.  If not, see
 * <http://www.gnu.org/licenses/>.
 */
// Warning this file was generated by a program.
#ifndef Sd2PinMap_h
#define Sd2PinMap_h

#if defined(_BOARD_MEGA_) || defined(_BOARD_UNO_)

	//Pin 11
	#define prtSDO				IOPORT_G
	#define	trisSDO				TRISG
	#define	latSDO				LATG
	#define	bnSDO				BIT_8

	//Pin 12
	#define prtSDI				IOPORT_G
	#define trisSDI				TRISG
	#define	latSDI				LATG
	#define bnSDI				BIT_7

	//Pin 13
	#define prtSCK				IOPORT_G
	#define trisSCK				TRISG
	#define latSCK				LATG
	#define bnSCK				BIT_6

#else
//*	Dec 14, 2011	<MLS>	Issue #160 this is the same, but we have to have a default, this still needs work

	//Pin 11
	#define prtSDO				IOPORT_G
	#define	trisSDO				TRISG
	#define	latSDO				LATG
	#define	bnSDO				BIT_8

	//Pin 12
	#define prtSDI				IOPORT_G
	#define trisSDI				TRISG
	#define	latSDI				LATG
	#define bnSDI				BIT_7

	//Pin 13
	#define prtSCK				IOPORT_G
	#define trisSCK				TRISG
	#define latSCK				LATG
	#define bnSCK				BIT_6

#endif

#endif